print('Addition: ', 1 + 2)
print('Substraction: ', 2 - 1)
print('Mulitplication: ', 2 * 3)
print('Division: ', 4 / 2)
print('Division: ', 6 / 2)
print('Division: ', 7 / 2)
print('Division without the remainder: ', 7 // 2)
print('Division without the remainder: ', 7 // 3)
print('Modulus: ', 3 % 2)
print('Exponentialiation: ', 2 ** 3)