print(3 > 2)
print(3 >= 2)
print(3 < 2)
print(2 < 3)
print(2 <= 3)
print(3 == 2)
print(3 != 2)
print(len('mango') == len('avocado'))
print(len('mango') != len('avocado'))
print(len('mango') < len('avocado'))
print(len('milk') != len('meat'))
print(len('milk') == len('meat'))
print(len('tomato') == len('potato'))
print(len('python') > len('dragon'))

print('True == True: ', True == True)
print('True == False: ', True == False)
print('False == False: ', False == False)

print('1 is 1: ', 1 is 1)
print('1 is not 2: ', 1 is not 2)
print('A in Asabeneh: ', 'A' in 'Asabeneh')
print('B in Asabeneh: ', 'B' in 'Asabeneh')
print('coding' in 'coding for all')
print('a in an: ', 'a' in 'an')
print('4 is 2 ** 2: ', 4 is 2 ** 2)