print(3 > 2 and 4 > 3)
print(3 > 2 and 4 < 3)
print(3 < 2 and 4 < 3)
print('True and True: ', True and True)
print(3 > 2 or 4 > 3)
print(3 > 2 or 4 < 3)
print(3 < 2 or 4 < 3)
print('True or False: ', True or False)
print(not 3 > 2)
print(not True)
print(not False)
print(not not True)
print(not not False)